name: Dev deployment from Github to AWS
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Images
        run: docker-compose build
      
      - name: List images
        run: docker images
        
      - name: Push Client Image to Docker Hub
        run: docker push cartermaclennan/engg4000:engg4000_client
      
      - name: Push Backend Image to Docker Hub
        run: docker push cartermaclennan/engg4000:engg4000_backend
        
      - name: Push Nginx Image to Docker Hub
        run: docker push cartermaclennan/engg4000:engg4000_nginx
 
